name: Build and Release MAUI App

on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Android workloads
      run: dotnet workload restore

    - name: Build APK
      run: |
        dotnet publish -f net8.0-android -c Release -r android-arm64 `
          -p:AndroidApplicationType=Apk `
          -p:PublishReadyToRun=false `
          --self-contained true `
          -o ./publish/android DnDClient.csproj

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: maui-apk
        path: ./publish/android/*.apk

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install Windows workloads
      run: dotnet workload restore

    - name: Publish Windows app (no MSIX, just exe)
      run: |
        dotnet publish -f net8.0-windows10.0.19041.0 -c Release `
          -p:WindowsPackageType=None `
          --self-contained true `
          -o ./publish/windows DnDClient.csproj

    - name: Install WiX Toolset
      run: choco install wixtoolset --version=3.11.2 -y

    - name: Create WiX installer definition
      run: |
        echo ^<?xml version="1.0" encoding="UTF-8"?^> > installer.wxs
        echo ^<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"^> >> installer.wxs
        echo   ^<Product Id="*" Name="DnDClient" Language="1033" Version="1.0.0.0" Manufacturer="Alexey Inc." UpgradeCode="PUT-GUID-HERE"^> >> installer.wxs
        echo     ^<Package InstallerVersion="500" Compressed="yes" InstallScope="perMachine" /^> >> installer.wxs
        echo     ^<MajorUpgrade DowngradeErrorMessage="A newer version is already installed." /^> >> installer.wxs
        echo     ^<MediaTemplate /^> >> installer.wxs
        echo     ^<Feature Id="ProductFeature" Title="DnDClient" Level="1"^> >> installer.wxs
        echo       ^<ComponentGroupRef Id="ProductComponents" /^> >> installer.wxs
        echo     ^</Feature^> >> installer.wxs
        echo   ^</Product^> >> installer.wxs
        echo   ^<Fragment^> >> installer.wxs
        echo     ^<Directory Id="TARGETDIR" Name="SourceDir"^> >> installer.wxs
        echo       ^<Directory Id="ProgramFilesFolder"^> >> installer.wxs
        echo         ^<Directory Id="INSTALLFOLDER" Name="DnDClient" /^> >> installer.wxs
        echo       ^</Directory^> >> installer.wxs
        echo     ^</Directory^> >> installer.wxs
        echo   ^</Fragment^> >> installer.wxs
        echo   ^<Fragment^> >> installer.wxs
        echo     ^<ComponentGroup Id="ProductComponents" Directory="INSTALLFOLDER"^> >> installer.wxs
        echo       ^<Component Id="MainExecutable" Guid="*"^> >> installer.wxs
        echo         ^<File Source="publish\\windows\\DnDClient.exe" /^> >> installer.wxs
        echo       ^</Component^> >> installer.wxs
        echo     ^</ComponentGroup^> >> installer.wxs
        echo   ^</Fragment^> >> installer.wxs
        echo ^</Wix^> >> installer.wxs

    - name: Build MSI
      run: |
        candle installer.wxs
        light installer.wixobj -o ./publish/windows/DnDClient.msi

    - name: Upload MSI artifact
      uses: actions/upload-artifact@v4
      with:
        name: maui-msi
        path: ./publish/windows/*.msi

  create-release:
    runs-on: ubuntu-latest
    needs: [build-android, build-windows]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download APK
      uses: actions/download-artifact@v4
      with:
        name: maui-apk
        path: ./artifacts/

    - name: Download MSI
      uses: actions/download-artifact@v4
      with:
        name: maui-msi
        path: ./artifacts/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./artifacts/*.apk
          ./artifacts/*.msi
        tag_name: ${{ github.sha }}
        name: Release ${{ github.sha }}
        body: |
          ## Новые фичи
          - Автоматическая сборка MAUI приложения.
          
          ## Артефакты
          - APK для Android
          - MSI для Windows
          
          Собрано на GitHub Actions.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
